package project.ui.admin.Reports;

import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.Cursor;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.ScrollPane;
import javafx.scene.layout.HBox;
import javafx.scene.layout.Priority;
import javafx.scene.layout.Region;
import javafx.scene.layout.VBox;
import project.model.Report;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

public class ReportPreviewPage {

    private static final String BG = "#0F0F0F";
    private static final String WHITE = "#1A1A1A";
    private static final String SOFT = "#1A1A1A";
    private static final String BORDER = "#F59E0B";
    private static final String HEADING = "#F3F4F6";
    private static final String TEXT = "#A1A1AA";
    private static final String MUTED = "#A1A1AA";
    private static final String BLUE = "#F59E0B";
    private static final String GREEN = "#22C55E";
    private static final String RED = "#EF4444";

    private final Report report;
    private final Runnable backAction;

    public ReportPreviewPage(Report report, Runnable backAction) {
        this.report = report;
        this.backAction = backAction;
    }

    public VBox getView() {
        VBox root = new VBox(18);
        root.setPadding(new Insets(28, 32, 32, 32));
        root.setStyle("-fx-background-color: " + BG + ";");

        Button back = outlineButton("← Back to Report Details");
        back.setOnAction(e -> {
            if (backAction != null) backAction.run();
        });

        Label title = new Label("Report Preview");
        title.setStyle("-fx-text-fill: " + HEADING + "; -fx-font-size: 29px; -fx-font-weight: bold;");
        Label subtitle = new Label("Preview the stored snapshot before exporting a PDF file.");
        subtitle.setStyle("-fx-text-fill: " + TEXT + "; -fx-font-size: 13px;");

        VBox preview = createPreviewCard();
        ScrollPane scroll = new ScrollPane(preview);
        scroll.setFitToWidth(true);
        scroll.setHbarPolicy(ScrollPane.ScrollBarPolicy.NEVER);
        scroll.setStyle("-fx-background-color: transparent; -fx-background: transparent;");
        VBox.setVgrow(scroll, Priority.ALWAYS);

        root.getChildren().addAll(back, title, subtitle, scroll);
        return root;
    }

    private VBox createPreviewCard() {
        VBox card = new VBox(16);
        card.setPadding(new Insets(30));
        card.setStyle("-fx-background-color: " + WHITE + "; -fx-border-color: " + BORDER + "; -fx-border-radius: 7; -fx-background-radius: 7;");

        if (report == null) {
            Label error = new Label("Report is not available.");
            error.setStyle("-fx-text-fill: " + RED + "; -fx-font-size: 15px; -fx-font-weight: bold;");
            card.getChildren().add(error);
            return card;
        }

        HBox brandRow = new HBox();
        brandRow.setAlignment(Pos.CENTER_LEFT);
        Label brand = new Label("ROADGUARDIAN");
        brand.setStyle("-fx-text-fill: " + BLUE + "; -fx-font-size: 22px; -fx-font-weight: bold;");
        Region spacer = new Region();
        HBox.setHgrow(spacer, Priority.ALWAYS);
        Label status = new Label(nonBlank(report.getStatus(), "Generated"));
        status.setStyle("-fx-text-fill: " + GREEN + "; -fx-background-color: " + GREEN + "18; -fx-border-radius: 14; -fx-background-radius: 14; -fx-padding: 5 9 5 9; -fx-font-size: 9px; -fx-font-weight: bold;");
        brandRow.getChildren().addAll(brand, spacer, status);

        Label name = new Label(nonBlank(report.getName(), "RoadGuardian Report"));
        name.setStyle("-fx-text-fill: " + HEADING + "; -fx-font-size: 20px; -fx-font-weight: bold;");

        VBox meta = new VBox(4);
        meta.getChildren().addAll(
                previewLine("Report ID", nonBlank(report.getReportId(), "-")),
                previewLine("Type", nonBlank(report.getType(), "-")),
                previewLine("Generated By", nonBlank(report.getGeneratedBy(), "Admin")),
                previewLine("Generated Date", nonBlank(report.getGeneratedDate(), "-")),
                previewLine("Snapshot Records", String.valueOf(report.getRecords()))
        );

        Label summaryTitle = sectionTitle("Summary");
        Label summary = new Label(nonBlank(report.getSummary(), "No summary available."));
        summary.setWrapText(true);
        summary.setStyle("-fx-text-fill: " + HEADING + "; -fx-font-size: 12px; -fx-background-color: " + SOFT + "; -fx-border-color: " + BORDER + "; -fx-border-radius: 8; -fx-background-radius: 8; -fx-padding: 12;");

        Label metricsTitle = sectionTitle("Metrics");
        VBox metrics = new VBox(7);
        for (Map.Entry<String, String> entry : report.getMetrics().entrySet()) {
            metrics.getChildren().add(previewLine(entry.getKey(), nonBlank(entry.getValue(), "-")));
        }
        if (metrics.getChildren().isEmpty()) {
            Label none = new Label("No metrics stored.");
            none.setStyle("-fx-text-fill: " + TEXT + "; -fx-font-size: 11px;");
            metrics.getChildren().add(none);
        }

        HBox actions = new HBox();
        actions.setAlignment(Pos.CENTER_RIGHT);
        Button pdf = primaryButton("Generate PDF");
        pdf.setOnAction(e -> generatePdf());
        actions.getChildren().add(pdf);

        card.getChildren().addAll(brandRow, name, meta, summaryTitle, summary, metricsTitle, metrics, actions);
        return card;
    }

    private HBox previewLine(String key, String value) {
        HBox row = new HBox(12);
        row.setPadding(new Insets(7, 9, 7, 9));
        row.setStyle("-fx-background-color: " + SOFT + "; -fx-border-color: " + BORDER + "; -fx-border-radius: 6; -fx-background-radius: 6;");
        Label k = new Label(key);
        k.setMinWidth(150);
        k.setStyle("-fx-text-fill: " + MUTED + "; -fx-font-size: 10px; -fx-font-weight: bold;");
        Label v = new Label(nonBlank(value, "-"));
        v.setWrapText(true);
        v.setStyle("-fx-text-fill: " + HEADING + "; -fx-font-size: 11px; -fx-font-weight: bold;");
        HBox.setHgrow(v, Priority.ALWAYS);
        row.getChildren().addAll(k, v);
        return row;
    }

    private Label sectionTitle(String text) {
        Label label = new Label(text);
        label.setStyle("-fx-text-fill: " + HEADING + "; -fx-font-size: 15px; -fx-font-weight: bold;");
        return label;
    }

    private void generatePdf() {
        if (report == null) return;

        try {
            File directory = new File(System.getProperty("user.home"), "RoadGuardianReports");
            if (!directory.exists() && !directory.mkdirs()) {
                throw new IllegalStateException("Unable to create RoadGuardianReports directory.");
            }

            String fileName = safeFileName(nonBlank(report.getName(), report.getReportId())) + ".pdf";
            File file = new File(directory, fileName);
            writeSimplePdf(file, buildPdfLines());

            Alert success = new Alert(Alert.AlertType.INFORMATION);
            success.setTitle("RoadGuardian");
            success.setHeaderText("PDF Generated");
            success.setContentText("Saved at:\n" + file.getAbsolutePath());
            success.showAndWait();
        } catch (Exception ex) {
            ex.printStackTrace();
            Alert error = new Alert(Alert.AlertType.ERROR);
            error.setTitle("RoadGuardian");
            error.setHeaderText("PDF Generation Failed");
            error.setContentText(ex.getMessage() == null ? "Unable to generate PDF." : ex.getMessage());
            error.showAndWait();
        }
    }

    private List<String> buildPdfLines() {
        List<String> lines = new ArrayList<>();
        lines.add("ROADGUARDIAN OPERATIONAL REPORT");
        lines.add("");
        lines.add("Name: " + nonBlank(report.getName(), "-"));
        lines.add("Report ID: " + nonBlank(report.getReportId(), "-"));
        lines.add("Type: " + nonBlank(report.getType(), "-"));
        lines.add("Generated By: " + nonBlank(report.getGeneratedBy(), "Admin"));
        lines.add("Generated Date: " + nonBlank(report.getGeneratedDate(), "-"));
        lines.add("Snapshot Records: " + report.getRecords());
        lines.add("");
        lines.add("SUMMARY");
        lines.addAll(wrap(nonBlank(report.getSummary(), "No summary available."), 85));
        lines.add("");
        lines.add("METRICS");
        for (Map.Entry<String, String> entry : report.getMetrics().entrySet()) {
            lines.addAll(wrap(entry.getKey() + ": " + nonBlank(entry.getValue(), "-"), 85));
        }
        return lines;
    }

    private void writeSimplePdf(File file, List<String> lines) throws Exception {
        StringBuilder content = new StringBuilder();
        content.append("BT\n/F1 11 Tf\n50 800 Td\n");
        int lineCount = 0;
        for (String raw : lines) {
            if (lineCount >= 45) break;
            String line = pdfEscape(ascii(raw));
            content.append("(").append(line).append(") Tj\n0 -16 Td\n");
            lineCount++;
        }
        content.append("ET\n");
        byte[] streamBytes = content.toString().getBytes(StandardCharsets.US_ASCII);

        ByteArrayOutputStream out = new ByteArrayOutputStream();
        List<Integer> offsets = new ArrayList<>();
        offsets.add(0);

        write(out, "%PDF-1.4\n");
        offsets.add(out.size());
        write(out, "1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n");
        offsets.add(out.size());
        write(out, "2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n");
        offsets.add(out.size());
        write(out, "3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>\nendobj\n");
        offsets.add(out.size());
        write(out, "4 0 obj\n<< /Length " + streamBytes.length + " >>\nstream\n");
        out.write(streamBytes);
        write(out, "endstream\nendobj\n");
        offsets.add(out.size());
        write(out, "5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n");

        int xref = out.size();
        write(out, "xref\n0 6\n");
        write(out, "0000000000 65535 f \n");
        for (int i = 1; i <= 5; i++) {
            write(out, String.format("%010d 00000 n \n", offsets.get(i)));
        }
        write(out, "trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n" + xref + "\n%%EOF\n");

        try (FileOutputStream stream = new FileOutputStream(file)) {
            stream.write(out.toByteArray());
        }
    }

    private void write(ByteArrayOutputStream out, String value) throws Exception {
        out.write(value.getBytes(StandardCharsets.US_ASCII));
    }

    private String ascii(String value) {
        if (value == null) return "";
        StringBuilder result = new StringBuilder();
        for (char c : value.toCharArray()) {
            result.append(c >= 32 && c <= 126 ? c : '?');
        }
        return result.toString();
    }

    private String pdfEscape(String value) {
        return value.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)");
    }

    private List<String> wrap(String text, int width) {
        List<String> lines = new ArrayList<>();
        String value = nonBlank(text, "-");
        while (value.length() > width) {
            int split = value.lastIndexOf(' ', width);
            if (split <= 0) split = width;
            lines.add(value.substring(0, split).trim());
            value = value.substring(split).trim();
        }
        lines.add(value);
        return lines;
    }

    private String safeFileName(String value) {
        String name = nonBlank(value, "RoadGuardian_Report");
        return name.replaceAll("[^a-zA-Z0-9._-]+", "_");
    }

    private Button outlineButton(String text) {
        Button button = new Button(text);
        button.setCursor(Cursor.HAND);
        button.setStyle("-fx-background-color: #1A1A1A; -fx-text-fill: " + BLUE + "; -fx-border-color: " + BLUE + "; -fx-border-radius: 8; -fx-background-radius: 8; -fx-padding: 9 14 9 14; -fx-font-size: 10px; -fx-font-weight: bold;");
        return button;
    }

    private Button primaryButton(String text) {
        Button button = new Button(text);
        button.setCursor(Cursor.HAND);
        button.setStyle("-fx-background-color: " + BLUE + "; -fx-text-fill: white; -fx-background-radius: 8; -fx-padding: 10 15 10 15; -fx-font-size: 11px; -fx-font-weight: bold;");
        return button;
    }

    private String nonBlank(String value, String fallback) {
        return value == null || value.trim().isEmpty() ? fallback : value.trim();
    }
}
