package project.ui.admin.Reports;

import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.Cursor;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.ScrollPane;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.HBox;
import javafx.scene.layout.Priority;
import javafx.scene.layout.Region;
import javafx.scene.layout.VBox;
import project.model.Report;
import project.ui.admin.DashBoard.AdminSectionPage;

import java.util.Map;

public class ReportDetailsPage extends AdminSectionPage {

    private static final String BG = "#0F0F0F";
    private static final String SURFACE = "#1A1A1A";
    private static final String SOFT = "#1A1A1A";
    private static final String BORDER = "#F59E0B";
    private static final String HEADING = "#F3F4F6";
    private static final String TEXT = "#A1A1AA";
    private static final String MUTED = "#A1A1AA";
    private static final String BLUE = "#F59E0B";
    private static final String GREEN = "#22C55E";

    private final Report report;
    private final Runnable onBack;
    private final Runnable onPreview;

    public ReportDetailsPage(Report report, Runnable onBack, Runnable onPreview) {
        this.report = report;
        this.onBack = onBack;
        this.onPreview = onPreview;
    }

    @Override
    public VBox getView() {
        VBox root = new VBox(18);
        root.setPadding(new Insets(28, 32, 32, 32));
        root.setStyle("-fx-background-color: " + BG + ";");

        Button back = outlineButton("← Back to Reports");
        back.setOnAction(e -> {
            if (onBack != null) onBack.run();
        });

        Label title = new Label("Report Details");
        title.setStyle("-fx-text-fill: " + HEADING + "; -fx-font-size: 29px; -fx-font-weight: bold;");
        Label subtitle = new Label("Stored Firebase snapshot and its calculated operational metrics.");
        subtitle.setStyle("-fx-text-fill: " + TEXT + "; -fx-font-size: 13px;");

        VBox content = report == null ? errorCard() : detailsCard();
        ScrollPane scroll = new ScrollPane(content);
        scroll.setFitToWidth(true);
        scroll.setHbarPolicy(ScrollPane.ScrollBarPolicy.NEVER);
        scroll.setStyle("-fx-background-color: transparent; -fx-background: transparent;");
        VBox.setVgrow(scroll, Priority.ALWAYS);

        root.getChildren().addAll(back, title, subtitle, scroll);
        return root;
    }

    private VBox detailsCard() {
        VBox card = new VBox(16);
        card.setPadding(new Insets(22));
        card.setStyle("-fx-background-color: " + SURFACE + "; -fx-border-color: " + BORDER + "; -fx-border-radius: 12; -fx-background-radius: 12;");

        HBox top = new HBox(10);
        top.setAlignment(Pos.CENTER_LEFT);
        VBox names = new VBox(3);
        Label name = new Label(nonBlank(report.getName(), "Unnamed Report"));
        name.setStyle("-fx-text-fill: " + HEADING + "; -fx-font-size: 21px; -fx-font-weight: bold;");
        Label id = new Label("Report ID: " + nonBlank(report.getReportId(), "-"));
        id.setStyle("-fx-text-fill: " + TEXT + "; -fx-font-size: 11px; -fx-font-weight: bold;");
        names.getChildren().addAll(name, id);
        Region spacer = new Region();
        HBox.setHgrow(spacer, Priority.ALWAYS);
        Label status = new Label(nonBlank(report.getStatus(), "Generated"));
        status.setStyle("-fx-text-fill: " + GREEN + "; -fx-background-color: " + GREEN + "18; -fx-border-color: " + GREEN + "55; -fx-border-radius: 14; -fx-background-radius: 14; -fx-padding: 5 10 5 10; -fx-font-size: 9px; -fx-font-weight: bold;");
        top.getChildren().addAll(names, spacer, status);

        HBox info = new HBox(10);
        VBox type = infoBox("TYPE", nonBlank(report.getType(), "-"));
        VBox generatedBy = infoBox("GENERATED BY", nonBlank(report.getGeneratedBy(), "Admin"));
        VBox date = infoBox("GENERATED DATE", nonBlank(report.getGeneratedDate(), "-"));
        VBox records = infoBox("SNAPSHOT RECORDS", String.valueOf(report.getRecords()));
        for (VBox box : new VBox[]{type, generatedBy, date, records}) HBox.setHgrow(box, Priority.ALWAYS);
        info.getChildren().addAll(type, generatedBy, date, records);

        Label summaryTitle = sectionTitle("Report Summary");
        Label summary = new Label(nonBlank(report.getSummary(), "No summary available."));
        summary.setWrapText(true);
        summary.setStyle("-fx-text-fill: " + HEADING + "; -fx-font-size: 12px; -fx-background-color: " + SOFT + "; -fx-border-color: " + BORDER + "; -fx-border-radius: 8; -fx-background-radius: 8; -fx-padding: 12;");

        Label metricsTitle = sectionTitle("Snapshot Metrics");
        GridPane metrics = createMetricsGrid();

        HBox actions = new HBox();
        actions.setAlignment(Pos.CENTER_RIGHT);
        Button preview = primaryButton("Preview / Generate PDF");
        preview.setOnAction(e -> {
            if (onPreview != null) onPreview.run();
        });
        actions.getChildren().add(preview);

        card.getChildren().addAll(top, info, summaryTitle, summary, metricsTitle, metrics, actions);
        return card;
    }

    private GridPane createMetricsGrid() {
        GridPane grid = new GridPane();
        grid.setHgap(10);
        grid.setVgap(10);

        int index = 0;
        for (Map.Entry<String, String> entry : report.getMetrics().entrySet()) {
            VBox box = infoBox(entry.getKey().toUpperCase(), nonBlank(entry.getValue(), "-"));
            box.setMinWidth(240);
            int col = index % 2;
            int row = index / 2;
            grid.add(box, col, row);
            GridPane.setHgrow(box, Priority.ALWAYS);
            index++;
        }

        if (index == 0) {
            Label none = new Label("No metrics were stored in this report.");
            none.setStyle("-fx-text-fill: " + TEXT + "; -fx-font-size: 11px;");
            grid.add(none, 0, 0);
        }
        return grid;
    }

    private VBox infoBox(String title, String value) {
        VBox box = new VBox(4);
        box.setPadding(new Insets(10));
        box.setMaxWidth(Double.MAX_VALUE);
        box.setStyle("-fx-background-color: " + SOFT + "; -fx-border-color: " + BORDER + "; -fx-border-radius: 8; -fx-background-radius: 8;");
        Label t = new Label(title);
        t.setStyle("-fx-text-fill: " + MUTED + "; -fx-font-size: 8px; -fx-font-weight: bold;");
        Label v = new Label(nonBlank(value, "-"));
        v.setWrapText(true);
        v.setStyle("-fx-text-fill: " + HEADING + "; -fx-font-size: 12px; -fx-font-weight: bold;");
        box.getChildren().addAll(t, v);
        return box;
    }

    private VBox errorCard() {
        VBox box = new VBox(7);
        box.setAlignment(Pos.CENTER);
        box.setPadding(new Insets(45));
        box.setStyle("-fx-background-color: " + SURFACE + "; -fx-border-color: " + BORDER + "; -fx-border-radius: 12; -fx-background-radius: 12;");
        Label title = new Label("Report not available");
        title.setStyle("-fx-text-fill: #EF4444; -fx-font-size: 16px; -fx-font-weight: bold;");
        box.getChildren().add(title);
        return box;
    }

    private Label sectionTitle(String text) {
        Label label = new Label(text);
        label.setStyle("-fx-text-fill: " + HEADING + "; -fx-font-size: 16px; -fx-font-weight: bold;");
        return label;
    }

    private Button outlineButton(String text) {
        Button button = new Button(text);
        button.setCursor(Cursor.HAND);
        button.setStyle("-fx-background-color: #1A1A1A; -fx-text-fill: " + BLUE + "; -fx-border-color: " + BLUE + "; -fx-border-radius: 8; -fx-background-radius: 8; -fx-padding: 9 14 9 14; -fx-font-size: 10px; -fx-font-weight: bold;");
        return button;
    }

    private Button primaryButton(String text) {
        Button button = new Button(text);
        button.setCursor(Cursor.HAND);
        button.setStyle("-fx-background-color: " + BLUE + "; -fx-text-fill: white; -fx-background-radius: 8; -fx-padding: 10 15 10 15; -fx-font-size: 11px; -fx-font-weight: bold;");
        return button;
    }

    private String nonBlank(String value, String fallback) {
        return value == null || value.trim().isEmpty() ? fallback : value.trim();
    }
}
